name: circuits
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ansi2html=1.8.0=py38h578d9bd_1
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=22.6.0=py38h06a4308_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38hfa26641_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.0.140=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.0.140=0
  - cuda-nsight-compute=12.0.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.0.140=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.0.146=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.0.146=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.0.140=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - dash=2.9.1=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - flask=1.1.2=pyh9f0ad1d_0
  - flask-compress=1.13=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.5.1.14=0
  - giflib=5.2.1=h5eee18b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.0=pyh210e3f2_0
  - ipython=8.10.0=pyh41d4057_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h7f8727e_0
  - jupyter-dash=0.4.2=pyhd8ed1ab_1
  - jupyter_core=5.2.0=py38h578d9bd_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.5.1.14=0
  - libcufile-dev=1.5.1.14=0
  - libcurand=10.3.1.124=0
  - libcurand-dev=10.3.1.124=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2022.4.1.6=0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.10.3=py38h06a4308_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.3.0=py38h6a678d5_2
  - pip=22.3.1=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - plotly=5.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - retrying=1.3.3=py_2
  - setuptools=65.6.3=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - torchaudio=0.13.1=py38_cu116
  - torchvision=0.14.1=py38_cu116
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - accelerate==0.17.1
    - aiofiles==22.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - aiosqlite==0.18.0
    - altair==5.0.1
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - async-timeout==4.0.2
    - attrs==22.2.0
    - babel==2.12.1
    - beautifulsoup4==4.12.0
    - bleach==6.0.0
    - cattrs==22.2.0
    - circuitsvis==0.0.0
    - cmake==3.26.4
    - commonmark==0.9.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==2.9.0
    - deepspeed==0.8.3
    - defusedxml==0.7.1
    - dill==0.3.6
    - distlib==0.3.6
    - docker-pycreds==0.4.0
    - einops==0.6.0
    - exceptiongroup==1.1.1
    - fancy-einsum==0.0.3
    - fastjsonschema==2.16.3
    - filelock==3.9.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - fst-pso==1.8.1
    - ftfy==6.1.1
    - fuzzytm==2.0.5
    - gensim==4.3.0
    - gitdb==4.0.10
    - gitpython==3.1.30
    - grpcio==1.51.3
    - hjson==3.1.0
    - huggingface-hub==0.12.0
    - importlib-metadata==5.2.0
    - importlib-resources==5.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jaxtyping==0.2.13
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.1.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-fileid==0.8.0
    - jupyter-server-terminals==0.4.4
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.3
    - jupyterlab==3.6.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.21.0
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - lit==16.0.6
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - miniful==0.0.6
    - mistune==2.0.5
    - ml-things==0.0.1
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.8.0
    - neel-plotly==0.0.0
    - networkx==3.0
    - ninja==1.11.1
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - openai==0.27.6
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - pathtools==0.1.2
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.16.0
    - protobuf==3.20.3
    - py-cpuinfo==9.0.0
    - pyarrow==11.0.0
    - pydantic==1.10.6
    - pyfume==0.2.25
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - python-rapidjson==1.10
    - pytorch-revgrad==0.2.0
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - ray==2.3.0
    - regex==2022.10.31
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==12.6.0
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sentry-sdk==1.15.0
    - setproctitle==1.3.2
    - simpful==2.9.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - sympy==1.12
    - tabulate==0.9.0
    - tdqm==0.0.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - toolz==0.12.0
    - torch==2.0.1
    - torchtyping==0.1.4
    - tornado==6.2
    - tqdm==4.64.1
    - transformer-lens==0.0.0
    - transformers==4.26.1
    - triton==2.0.0
    - tritonclient==2.31.0
    - trlx==0.5.0
    - typeguard==3.0.2
    - uri-template==1.2.0
    - virtualenv==20.21.0
    - wandb==0.13.10
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - xxhash==3.2.0
    - y-py==0.5.9
    - yarl==1.8.2
    - ypy-websocket==0.8.2
    - zipp==3.14.0
prefix: /home/curttigges/miniconda3/envs/circuits
